workflows:
  android-debug:
    name: Android Debug APK

    environment:
      node: 22

    scripts:
      - npm ci
      - npx cap sync android
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk